/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Todo App API specification
 * OpenAPI spec version: 0.1.0
 */
import type { TaskStatsByPriority } from "./taskStatsByPriority";
export interface TaskStats {
    total: number;
    completed: number;
    pending: number;
    byPriority: TaskStatsByPriority;
    overdue: number;
}
//# sourceMappingURL=taskStats.d.ts.map