/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Todo App API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List all tasks for the authenticated user
 */
export declare const ListTasksQueryParams: zod.ZodObject<{
    priority: zod.ZodOptional<zod.ZodEnum<["low", "medium", "high"]>>;
    completed: zod.ZodOptional<zod.ZodBoolean>;
    sortBy: zod.ZodOptional<zod.ZodEnum<["priority", "createdAt", "dueDate", "title"]>>;
    sortOrder: zod.ZodOptional<zod.ZodEnum<["asc", "desc"]>>;
}, "strip", zod.ZodTypeAny, {
    priority?: "low" | "medium" | "high" | undefined;
    completed?: boolean | undefined;
    sortBy?: "priority" | "createdAt" | "dueDate" | "title" | undefined;
    sortOrder?: "asc" | "desc" | undefined;
}, {
    priority?: "low" | "medium" | "high" | undefined;
    completed?: boolean | undefined;
    sortBy?: "priority" | "createdAt" | "dueDate" | "title" | undefined;
    sortOrder?: "asc" | "desc" | undefined;
}>;
export declare const ListTasksResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}>;
export declare const ListTasksResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a new task
 */
export declare const createTaskBodyTitleMax = 255;
export declare const createTaskBodyPriorityDefault = "medium";
export declare const CreateTaskBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    priority: zod.ZodDefault<zod.ZodEnum<["low", "medium", "high"]>>;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
}, "strip", zod.ZodTypeAny, {
    priority: "low" | "medium" | "high";
    title: string;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}, {
    title: string;
    priority?: "low" | "medium" | "high" | undefined;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}>;
/**
 * @summary Get a task by ID
 */
export declare const GetTaskParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetTaskResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}>;
/**
 * @summary Update a task
 */
export declare const UpdateTaskParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const updateTaskBodyTitleMax = 255;
export declare const UpdateTaskBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    priority: zod.ZodOptional<zod.ZodEnum<["low", "medium", "high"]>>;
    completed: zod.ZodOptional<zod.ZodBoolean>;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
}, "strip", zod.ZodTypeAny, {
    priority?: "low" | "medium" | "high" | undefined;
    completed?: boolean | undefined;
    dueDate?: Date | null | undefined;
    title?: string | undefined;
    description?: string | null | undefined;
}, {
    priority?: "low" | "medium" | "high" | undefined;
    completed?: boolean | undefined;
    dueDate?: Date | null | undefined;
    title?: string | undefined;
    description?: string | null | undefined;
}>;
export declare const UpdateTaskResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}>;
/**
 * @summary Delete a task
 */
export declare const DeleteTaskParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Toggle task completion status
 */
export declare const ToggleTaskCompleteParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const ToggleTaskCompleteResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}, {
    priority: "low" | "medium" | "high";
    completed: boolean;
    createdAt: Date;
    title: string;
    id: number;
    userId: string;
    updatedAt: Date;
    dueDate?: Date | null | undefined;
    description?: string | null | undefined;
}>;
/**
 * @summary Get task statistics for dashboard
 */
export declare const GetTaskStatsResponse: zod.ZodObject<{
    total: zod.ZodNumber;
    completed: zod.ZodNumber;
    pending: zod.ZodNumber;
    byPriority: zod.ZodObject<{
        low: zod.ZodNumber;
        medium: zod.ZodNumber;
        high: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        low: number;
        medium: number;
        high: number;
    }, {
        low: number;
        medium: number;
        high: number;
    }>;
    overdue: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    completed: number;
    total: number;
    pending: number;
    byPriority: {
        low: number;
        medium: number;
        high: number;
    };
    overdue: number;
}, {
    completed: number;
    total: number;
    pending: number;
    byPriority: {
        low: number;
        medium: number;
        high: number;
    };
    overdue: number;
}>;
//# sourceMappingURL=api.d.ts.map