/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Todo App API specification
 * OpenAPI spec version: 0.1.0
 */
export type UpdateTaskBodyPriority = (typeof UpdateTaskBodyPriority)[keyof typeof UpdateTaskBodyPriority];
export declare const UpdateTaskBodyPriority: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
};
//# sourceMappingURL=updateTaskBodyPriority.d.ts.map