/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Todo App API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority];

export const TaskPriority = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export interface Task {
  id: number;
  userId: string;
  title: string;
  description?: string | null;
  priority: TaskPriority;
  completed: boolean;
  dueDate?: string | null;
  createdAt: string;
  updatedAt: string;
}

export type CreateTaskBodyPriority =
  (typeof CreateTaskBodyPriority)[keyof typeof CreateTaskBodyPriority];

export const CreateTaskBodyPriority = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export interface CreateTaskBody {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  description?: string | null;
  priority?: CreateTaskBodyPriority;
  dueDate?: string | null;
}

export type UpdateTaskBodyPriority =
  (typeof UpdateTaskBodyPriority)[keyof typeof UpdateTaskBodyPriority];

export const UpdateTaskBodyPriority = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export interface UpdateTaskBody {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
  description?: string | null;
  priority?: UpdateTaskBodyPriority;
  completed?: boolean;
  dueDate?: string | null;
}

export type TaskStatsByPriority = {
  low: number;
  medium: number;
  high: number;
};

export interface TaskStats {
  total: number;
  completed: number;
  pending: number;
  byPriority: TaskStatsByPriority;
  overdue: number;
}

export interface ErrorResponse {
  error: string;
}

export type ListTasksParams = {
  priority?: ListTasksPriority;
  completed?: boolean;
  sortBy?: ListTasksSortBy;
  sortOrder?: ListTasksSortOrder;
};

export type ListTasksPriority =
  (typeof ListTasksPriority)[keyof typeof ListTasksPriority];

export const ListTasksPriority = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export type ListTasksSortBy =
  (typeof ListTasksSortBy)[keyof typeof ListTasksSortBy];

export const ListTasksSortBy = {
  priority: "priority",
  createdAt: "createdAt",
  dueDate: "dueDate",
  title: "title",
} as const;

export type ListTasksSortOrder =
  (typeof ListTasksSortOrder)[keyof typeof ListTasksSortOrder];

export const ListTasksSortOrder = {
  asc: "asc",
  desc: "desc",
} as const;
