/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Todo App API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all tasks for the authenticated user
 */
export const ListTasksQueryParams = zod.object({
  priority: zod.enum(["low", "medium", "high"]).optional(),
  completed: zod.coerce.boolean().optional(),
  sortBy: zod.enum(["priority", "createdAt", "dueDate", "title"]).optional(),
  sortOrder: zod.enum(["asc", "desc"]).optional(),
});

export const ListTasksResponseItem = zod.object({
  id: zod.number(),
  userId: zod.string(),
  title: zod.string(),
  description: zod.string().nullish(),
  priority: zod.enum(["low", "medium", "high"]),
  completed: zod.boolean(),
  dueDate: zod.coerce.date().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const ListTasksResponse = zod.array(ListTasksResponseItem);

/**
 * @summary Create a new task
 */
export const createTaskBodyTitleMax = 255;

export const createTaskBodyPriorityDefault = `medium`;

export const CreateTaskBody = zod.object({
  title: zod.string().min(1).max(createTaskBodyTitleMax),
  description: zod.string().nullish(),
  priority: zod
    .enum(["low", "medium", "high"])
    .default(createTaskBodyPriorityDefault),
  dueDate: zod.coerce.date().nullish(),
});

/**
 * @summary Get a task by ID
 */
export const GetTaskParams = zod.object({
  id: zod.coerce.number(),
});

export const GetTaskResponse = zod.object({
  id: zod.number(),
  userId: zod.string(),
  title: zod.string(),
  description: zod.string().nullish(),
  priority: zod.enum(["low", "medium", "high"]),
  completed: zod.boolean(),
  dueDate: zod.coerce.date().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Update a task
 */
export const UpdateTaskParams = zod.object({
  id: zod.coerce.number(),
});

export const updateTaskBodyTitleMax = 255;

export const UpdateTaskBody = zod.object({
  title: zod.string().min(1).max(updateTaskBodyTitleMax).optional(),
  description: zod.string().nullish(),
  priority: zod.enum(["low", "medium", "high"]).optional(),
  completed: zod.boolean().optional(),
  dueDate: zod.coerce.date().nullish(),
});

export const UpdateTaskResponse = zod.object({
  id: zod.number(),
  userId: zod.string(),
  title: zod.string(),
  description: zod.string().nullish(),
  priority: zod.enum(["low", "medium", "high"]),
  completed: zod.boolean(),
  dueDate: zod.coerce.date().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Delete a task
 */
export const DeleteTaskParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Toggle task completion status
 */
export const ToggleTaskCompleteParams = zod.object({
  id: zod.coerce.number(),
});

export const ToggleTaskCompleteResponse = zod.object({
  id: zod.number(),
  userId: zod.string(),
  title: zod.string(),
  description: zod.string().nullish(),
  priority: zod.enum(["low", "medium", "high"]),
  completed: zod.boolean(),
  dueDate: zod.coerce.date().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Get task statistics for dashboard
 */
export const GetTaskStatsResponse = zod.object({
  total: zod.number(),
  completed: zod.number(),
  pending: zod.number(),
  byPriority: zod.object({
    low: zod.number(),
    medium: zod.number(),
    high: zod.number(),
  }),
  overdue: zod.number(),
});
