/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Todo App API specification
 * OpenAPI spec version: 0.1.0
 */
import type { CreateTaskBodyPriority } from "./createTaskBodyPriority";

export interface CreateTaskBody {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  description?: string | null;
  priority?: CreateTaskBodyPriority;
  dueDate?: Date | null;
}
